### ISSUE TITLE
Css background URL

### ISSUE THREAD

**Issue by oalkandev** [izica/html-sass-babel-webpack-boilerplate#1]
When i build project, css background image urls not match with /dist folder hierachy so imges not shown.

Example: 
 i using in development like: url('assets/img/logo.png')

it builded same like that development: url('assets/img/logo.png')

Expectation is: url('../img/logo.png')

**Comment by izica** [comment]
Hello, try to use in development like url('../img/logo.png')
This example is valid `background-image: url('../img/cat.jpg');`
**https://github.com/izica/html-sass-babel-webpack-boilerplate/blob/master/src/scss/module/cat.scss**

**Comment by oalkandev** [comment]
Actually i dont know why when i try that before opened this issue but nothing changed and it works like as you said :) 
I think i missed something, thank you :)
