### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by oalkandev** [izica/html-sass-babel-webpack-boilerplate#2]
I'm adding to error message i think that happen add new .html file to project. If you need to show file i will share my private github repo with contributers.

Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed (from ./webpack/loader/html-loader.js):
  RangeError: Maximum call stack size exceeded
  
  - html-loader.js:10 resolve
    C:/code/sevimlikutu-html/webpack/loader/html-loader.js:10:38
  
  - Array.forEach
  
  - html-loader.js:9 forEach
    C:/code/sevimlikutu-html/webpack/loader/html-loader.js:9:18
  
  - html-loader.js:12 insertIncludes
    C:/code/sevimlikutu-html/webpack/loader/html-loader.js:12:30
  
  - Array.forEach
  
  - html-loader.js:9 forEach
    C:/code/sevimlikutu-html/webpack/loader/html-loader.js:9:18
  
  - html-loader.js:12 insertIncludes
    C:/code/sevimlikutu-html/webpack/loader/html-loader.js:12:30
  
  - Array.forEach
  
  
  - RangeError: Maximum call stack size exceeded
  
  - compiler.js:79 childCompiler.runAsChild
    [sevimlikutu-html]/[html-webpack-plugin]/lib/compiler.js:79:16
  
  - Compiler.js:306 compile
    [sevimlikutu-html]/[webpack]/lib/Compiler.js:306:11
  
  - Compiler.js:631 hooks.afterCompile.callAsync.err
    [sevimlikutu-html]/[webpack]/lib/Compiler.js:631:15
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [sevimlikutu-html]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:628 compilation.seal.err
    [sevimlikutu-html]/[webpack]/lib/Compiler.js:628:31
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [sevimlikutu-html]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1329 hooks.optimizeAssets.callAsync.err
    [sevimlikutu-html]/[webpack]/lib/Compilation.js:1329:35

**Comment by izica** [comment]
Hi, yep, share your repo, please

**Comment by oalkandev** [comment]
Here is https://github.com/oalkandev/sevimlikutu-html

You can clone pages like as sign.html and try run or build
